AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  VpcId:
    Type: String
  Subnet1:
    Type: String
  Subnet2:
    Type: String
  TaskExecutionRoleArn:
    Type: String
  ContainerImage:
    Type: String
  ClusterName:
    Type: String

Resources:
  TaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: hello-world-task
      Cpu: 256
      Memory: 512
      NetworkMode: awsvpc
      RequiresCompatibilities: [FARGATE]
      ExecutionRoleArn: !Ref TaskExecutionRoleArn
      ContainerDefinitions:
        - Name: hello-container
          Image: !Ref ContainerImage
          PortMappings:
            - ContainerPort: 3000

  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Subnets: [!Ref Subnet1, !Ref Subnet2]
      SecurityGroups: []
      Scheme: internet-facing
      Type: application

  TargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      VpcId: !Ref VpcId
      Port: 3000
      Protocol: HTTP
      TargetType: ip
      HealthCheckPath: /

  Listener:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      DefaultActions:
        - Type: forward
          TargetGroupArn: !Ref TargetGroup
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: HTTP

  ECSService:
    Type: AWS::ECS::Service
    DependsOn: Listener
    Properties:
      Cluster: !Ref ClusterName
      LaunchType: FARGATE
      DesiredCount: 1
      TaskDefinition: !Ref TaskDefinition
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets: [!Ref Subnet1, !Ref Subnet2]
          AssignPublicIp: ENABLED
      LoadBalancers:
        - ContainerName: hello-container
          ContainerPort: 3000
          TargetGroupArn: !Ref TargetGroup

Outputs:
  ServiceName:
    Value: !Ref ECSService
  TaskDefinitionArn:
    Value: !Ref TaskDefinition

