version: 2.1

executors:
  docker-executor:
    docker:
      - image: cimg/aws:2023.12

jobs:
  build-and-deploy:
    executor: docker-executor
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Login to ECR
          command: |
            aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - run:
          name: Build & Push Docker Image
          command: |
            IMAGE_TAG="${CIRCLE_SHA1:0:7}"
            docker build -t $ECR_REPO_NAME:$IMAGE_TAG ./app
            docker tag $ECR_REPO_NAME:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/$ECR_REPO_NAME:$IMAGE_TAG
      - run:
          name: Deploy to ECS
          command: |
            aws ecs update-service --cluster $CLUSTER_NAME --service $SERVICE_NAME --force-new-deployment

workflows:
  version: 2
  deploy:
    jobs:
      - build-and-deploy

